### ISSUE TITLE
Tommy Brennan- Project Plan

### ISSUE THREAD

**Issue by tommymb** [tommymb/web-design-2-independent-project#1]
I created a PDF with everything in one, but it won't allow me to attach it to this issue so I'm attaching everything separately.

Along with my wireframe, I created a high fidelity prototype of my website on XD. I did this for my own sake since I find it easier to see a very detailed version of the website while I code.

[Sitemap.pdf](https://github.com/tommymb/web-design-2-independent-project/files/7566339/Sitemap.pdf)
[Content inventory.pdf](https://github.com/tommymb/web-design-2-independent-project/files/7566340/Content.inventory.pdf)
[Securiteam site moodboards.pdf](https://github.com/tommymb/web-design-2-independent-project/files/7566341/Securiteam.site.moodboards.pdf)
[Logo.pdf](https://github.com/tommymb/web-design-2-independent-project/files/7566342/Logo.pdf)
[Wireframe.pdf](https://github.com/tommymb/web-design-2-independent-project/files/7566356/Wireframe.pdf)
[Securiteam High Fidelity.pdf](https://github.com/tommymb/web-design-2-independent-project/files/7566357/Securiteam.High.Fidelity.pdf)

**Comment by thatkidmadrid** [comment]
| | 0 points | 1 points | 2 points | 3 points | Grade |
| --- | --- | --- | --- | --- | --- |
| **Content inventory** | Incomplete or missing | Rushed & too generic | Specific but obviously lacking research | Specific and appropriate, with good details | 3 |
| **Sitemap** | Incomplete or missing | Has only the pages we’re coding | Lots of important pages missing | Complete, organized and contains all necessary pages | 3 |
| **Homepage wireframe** | Incomplete or missing | Missing important pieces or poorly executed | Complete but not detailed enough | Complete, detailed, responsive, and a good representation to code from | 3 |
| **Page 2 wireframe** | Incomplete or missing | Missing important pieces or poorly executed | Complete but not detailed enough | Complete, detailed, responsive, and a good representation to code from | 3 |
| **Page 3 wireframe** | Incomplete or missing | Missing important pieces or poorly executed | Complete but not detailed enough | Complete, detailed, responsive, and a good representation to code from | 3 |
| **Logo** | Incomplete or missing | Only works well at one size | Small sizes are inconsistent with large sizes | Cohesive & uniform for all sizes, even if different | 2 |
| **Visual design** | Incomplete or missing | Missing important components or poorly executed | Average, could be more cohesive & considered | Cohesive & appropriate with a good sample of components | 2 |
| **Professionalism** | Rushed & poorly done | Okay | Average, could use more time spent | Clearly demonstrated lots of effort and consideration | 3 |
